name: Kernel Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v4

    - name: Set up MemKernel as a module (M-OUT) with specified name
      run: |
        curl -LSs "https://raw.githubusercontent.com/Poko-Apps/MemKernel/main/kernel/setup.sh" | bash -s M dogi

    - name: Android kernel build
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        NAME: Loganysl
      with:
        arch: arm64
        compiler: clang/11/binutils
        defconfig: gta4lve_eur_open_defconfig
        # [تم التصحيح هنا] إضافة modules لضمان أن المترجم سيقوم ببناء ملفات .ko 
        image: Image.gz-dtb modules

    - name: Upload Kernel and Module
      uses: actions/upload-artifact@v4
      with:
        name: moduleandkernel
        path: |
          ${{ steps.build.outputs.outfile }}
          # [تم التصحيح هنا] تغيير المسار والاسم ليتطابق مع "dogi" واستخدام النجمة لضمان التقاط الملف
          ./out/drivers/dogi/*.ko
